import * as Dialog from "@radix-ui/react-dialog";
import { Copy, Download, X } from "lucide-react";
import jsPDF from "jspdf";

export default function AILetterModal({ open, onClose, letterText, issue, notify }) {
  const copyLetter = async () => {
    await navigator.clipboard.writeText(letterText);
    notify("Letter copied.");
  };

  const downloadPdf = () => {
    const pdf = new jsPDF({ unit: "pt", format: "a4" });
    const lines = pdf.splitTextToSize(letterText, 500);
    pdf.setFont("times", "normal");
    pdf.setFontSize(12);
    pdf.text(lines, 48, 62);
    pdf.save(`${issue?.title || "civic-letter"}.pdf`);
    notify("PDF downloaded.");
  };

  return (
    <Dialog.Root open={open} onOpenChange={(next) => !next && onClose()}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-black/75 backdrop-blur-xl" />
        <Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[min(920px,92vw)] -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-3xl border border-[#A855F7]/30 bg-[#0A0015]/95 shadow-[0_0_90px_rgba(168,85,247,.35)]">
          <div className="flex items-center justify-between border-b border-[#A855F7]/20 p-5">
            <div>
              <Dialog.Title className="text-xl font-black">Official Complaint Letter</Dialog.Title>
              <Dialog.Description className="text-sm text-[#94A3B8]">Professional municipal escalation generated by CivicPulse AI</Dialog.Description>
            </div>
            <Dialog.Close className="rounded-xl p-2 text-[#94A3B8] transition hover:bg-white/10 hover:text-white">
              <X size={20} />
            </Dialog.Close>
          </div>
          <div className="max-h-[62vh] overflow-auto p-6">
            <div className="paper rounded-2xl p-8 font-mono text-sm leading-7">
              <div className="mb-6 border-b border-slate-300 pb-4 text-center">
                <div className="text-lg font-black uppercase tracking-[0.18em]">CivicPulse AI Letterhead</div>
                <div className="text-xs uppercase tracking-[0.16em] text-slate-500">Community Hero Platform</div>
              </div>
              <pre className="whitespace-pre-wrap font-mono">{letterText}</pre>
            </div>
          </div>
          <div className="flex flex-wrap justify-end gap-3 border-t border-[#A855F7]/20 p-5">
            <button onClick={copyLetter} className="flex items-center gap-2 rounded-xl border border-[#A855F7]/30 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/10">
              <Copy size={16} /> Copy
            </button>
            <button onClick={downloadPdf} className="btn-primary flex items-center gap-2">
              <Download size={16} /> Download PDF
            </button>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
